Repository boostcampwm-snu-2025/netflix-clone, pull requests merged in 2025-09, with the labels that each got.

#5 [식물생산과학부_이형진] 넷플릭스 클론 프로젝트
  README.md
  index.html
  main.css
  main.js
Labels: Header영역, 본문영역

#8 [조경지역시스템공학부_김연우] 넷플릭스 메인 페이지 UI 클론코딩
  assets/20th_thumbnail.webp
  assets/Netflix_Logo_RGB.png
  assets/chef_thumbnail.webp
  assets/down_arrow.svg
  assets/esquire_thumbnail.webp
  assets/hero_thumbnail.webp
  assets/hero_title.webp
  assets/history_thumbnail.webp
  assets/horse_lover_thumbnail.webp
  assets/info.svg
  assets/kiss_thumbnail.webp
  assets/kpop_thumbnail.webp
  assets/my_profile.jpeg
  assets/notification_icon.svg
  assets/play.svg
  assets/pokssak_thumbnail.webp
  assets/samagui_thumbnail.webp
  assets/search_icon.svg
  assets/trigger_thumbnail.webp
  assets/try_thumbnail.webp
  assets/yadang_thumbnail.webp
  index.html
  src/components/header/main-header-kids-button.js
  src/components/header/main-header-menu.js
  src/components/header/main-header-my-profile-button.js
  src/components/header/main-header-notification-button.js
  src/components/header/main-header-search-button.js
  src/components/header/main-header.js
  src/entity/asset.js
  src/entity/main-header-data.js
  src/entity/route.js
  src/feature/header/format-badge-number.js
  src/main.js
  style/container.css
  style/global.css
  style/header.css
  style/hero.css
  style/recommendation.css
  style/reset.css
  style/topten.css
Labels: Header영역, 본문영역

#9 [지구환경과학부_최원진] - 넷플릭스 클론코딩
  images/card-01.jpg
  images/card-02.jpg
  images/card-03.jpg
  images/card-04.jpg
  images/card-05.jpg
  images/card-06.jpg
  images/card-07.jpg
  images/card-08.jpg
  images/card-09.jpg
  images/card-10.jpg
  images/card-11.jpg
  images/card-12.jpg
  images/card-13.jpg
  images/card-14.jpg
  images/card-15.jpg
  images/card-16.jpg
  images/card-17.jpg
  images/card-18.jpg
  images/hero.jpg
  index.html
  style.css
Labels: Header영역, 본문영역

#11 [전기정보공학부_김경준] 넷플릭스 메인 레이아웃 구현
  .nvmrc
  README.md
  assets/footer/facebook.svg
  assets/footer/instagram.svg
  assets/footer/twitter.svg
  assets/footer/youtube.svg
  assets/header/netflix-logo.svg
  assets/header/notification-icon.svg
  assets/header/profile-icon.png
  assets/header/search-icon.svg
  assets/main/billboard-title.png
  assets/main/hero-background.png
  assets/main/info.svg
  assets/main/movies/1.png
  assets/main/movies/2.png
  assets/main/movies/3.png
  assets/main/movies/4.png
  assets/main/movies/5.png
  assets/main/movies/6.png
  assets/main/new/1.png
  assets/main/new/2.png
  assets/main/new/3.png
  assets/main/new/4.png
  assets/main/new/5.png
  assets/main/new/6.png
  assets/main/play.svg
  assets/main/rank/1.svg
  assets/main/rank/2.svg
  assets/main/rank/3.svg
  assets/main/rank/4.svg
  assets/main/rank/5.svg
  assets/main/rank/6.svg
  assets/main/series/1.png
  assets/main/series/2.png
  assets/main/series/3.png
  assets/main/series/4.png
  assets/main/series/5.png
  assets/main/series/6.png
  css/footer.css
  css/global.css
  css/header.css
  css/main.css
  index.html
  js/main.js
Labels: Header영역, 본문영역

#16 [지구환경과학부_편채범] - Netflix 메인페이지 정적 레이아웃 구현
  README.md
  img/240_F_554944812_zVVODG8Qgfzl08ScezL4H9D9gFrgPAnW.jpg
  img/attack-on-titan.jpg
  img/attack-on-titan.png
  img/banner-attack-on-titan.webp
  img/icon/Netflix-Logo.jpg
  img/icon/Netflix-Logo.png
  img/icon/facebook-black.jpg
  img/icon/facebook-black.png
  img/icon/free-icon-notification-bell-12328821.png
  img/icon/free-icon-search-149852.png
  img/icon/instagram-black.jpg
  img/icon/instagram-black.png
  img/icon/twitter-black.jpg
  img/icon/user-icon.png
  img/icon/youtube-black.jpg
  img/poster/adolescence.jpg
  img/poster/aema.jpg
  img/poster/better-call-saul.jpg
  img/poster/bon-appétit--Your-majesty.webp
  img/poster/breaking-bad.webp
  img/poster/demon-slayer-vertical.webp
  img/poster/demon-slayer.webp
  img/poster/designated-survivor.jpg
  img/poster/esquire.webp
  img/poster/eunjung-and-sangyeon.jpg
  img/poster/little-island-big-hero.webp
  img/poster/my-turn.webp
  img/poster/queen-mantis.webp
  img/poster/signal.webp
  img/poster/suriname.jpg
  img/poster/the-glory.jpg
  img/poster/the-secrete-forest.webp
  img/poster/trigger.jpg
  img/poster/wednesday-vertical.jpg
  img/poster/wednesday.jpg
  src/index.html
  src/style.css
Labels: Header영역, 본문영역

#17 [자유전공학부_강수민] 넷플릭스 정적 메인페이지 클론코딩
  README.md
  index.html
  src/hero.png
  src/poster.png
  src/profile.png
  style.css
Labels: Header영역, 본문영역

#22 [컴퓨터공학부_변민규] - netflix clone page 완성
  images/hero_image.webp
  images/hero_image_title.webp
  images/korean1.webp
  images/korean2.jpg
  images/korean3.jpg
  images/korean4.jpg
  images/korean5.webp
  images/korean6.webp
  images/top 10 3.webp
  images/top 10 4.jpg
  images/top 10 5.webp
  images/top10 2.webp
  images/top10 6.webp
  images/top10.webp
  images/대한민국 top10_2.webp
  images/대한민국 top10_3.webp
  images/대한민국 top10_4.webp
  images/대한민국 top10_5.jpg
  images/대한민국 top10_6.webp
  images/대한민국top10_1.webp
  index.html
  styles.css
Labels: Header영역, 본문영역

#23 [인공지능 협동과정_최진영] 넷플릭스 클론 코딩 (정적 요소)
  src/app.js
  src/index.html
  src/styles.css
Labels: Header영역, 본문영역

#25 [컴퓨터공학부_현주영] - 넷플릭스 클론
  img/hero-img.webp
  img/logo.png
  img/profile.png
  img/rick-and-morty.webp
  img/title-card.webp
  index.html
  styles.css
Labels: Header영역, 본문영역

#24 [자유전공학부_곽승연] - 넷플릭스 클론 코딩
  README.md
  claude.txt
  css/category.css
  css/footer.css
  css/header.css
  css/hero.css
  css/style.css
  images/bell.png
  images/drama1.jpg
  images/drama2.jpg
  images/drama3.jpg
  images/drama4.jpg
  images/drama5.jpg
  images/drama6.jpg
  images/ghibli1.jpg
  images/ghibli2.jpg
  images/ghibli3.jpg
  images/ghibli4.jpg
  images/ghibli5.jpg
  images/ghibli6.jpg
  images/neflix.png
  images/poster.webp
  images/search.png
  images/shin-chan1.jpg
  images/shin-chan2.jpg
  images/shin-chan3.jpg
  images/shin-chan4.jpg
  images/shin-chan5.jpg
  images/shin-chan6.jpg
  images/user.png
  index.html
Labels: Header영역, 본문영역

#30 [지구환경과학부_편채범] - Netflix 클론 헤더 드롭다운 및 무한 슬라이더 구현
  README.md
  src/index.html
  src/script/modal.js
  src/script/slider_carousel.js
  src/style/global.css
  src/style/style.css
Labels: 나만의체크포인트, 2-modal, 2-slider, 2-carousel

#32 [전기정보공학부_김희원] 나만의 체크포인트와 반응형 넷플릭스 구현
  README.md
  app.js
  index.html
  styles.css
Labels: 나만의체크포인트, 2-carousel

#35 [컴퓨터공학부_류명현] - 3주차 체크포인트
  README.md
  src/app.js
  src/main.html
  src/modal-slider.css
  src/modules/modal.js
Labels: 나만의체크포인트, Header영역, 2-modal

#37 [컴퓨터공학부_변민규] - 3주차 체크포인트/3주차 넷플릭스
  .DS_Store
  README.md
  images/.DS_Store
  images/korean10.jpg
  images/korean11.jpg
  images/korean12.jpg
  images/korean13.jpg
  images/korean14.jpg
  images/korean15.jpg
  images/korean7.webp
  images/korean8.jpg
  images/korean9.jpg
  images/notification_image/나는생존자다.jpg
  images/notification_image/에스콰이어.jpg
  images/notification_image/웬즈데이.jpg
  images/notification_image/은중과상연.jpg
  images/notification_image/트리거.jpg
  images/top10_1.webp
  images/top10_10.jpg
  images/top10_11.jpg
  images/top10_12.jpg
  images/top10_13.jpg
  images/top10_14.jpg
  images/top10_15.jpg
  images/top10_2.webp
  images/top10_3.webp
  images/top10_4.jpg
  images/top10_5.webp
  images/top10_6.webp
  images/top10_7.jpg
  images/top10_7.webp
  images/top10_8.jpg
  images/top10_9.jpg
  images/대한민국 top10_7.webp
  images/대한민국 top10_8.webp
  images/대한민국 top10_9.webp
  index.html
  js/CardSlider.js
  js/app.js
  js/carousel.js
  js/examples.js
  js/header.js
  js/pagination.js
  styles.css
Labels: 나만의체크포인트, Header영역, 2-modal, 2-slider, 2-carousel

#39 [컴퓨터공학부_현주영]_3주차 체크포인트
  README.md
  components/dropdown.js
  components/slider.js
  img/breaking-bad.webp
  img/cat.jpg
  img/dexter.webp
  img/gossip-girl.webp
  img/inside-job.jpg
  img/knives-out.webp
  index.html
  styles.css
Labels: 나만의체크포인트

#45 [지구환경과학부_최원진] 모달, 슬라이딩 기능 추가
  images/profile.jpg
  index.html
  src/app.js
  src/modal.js
  src/slider.js
  style.css
Labels: 2-modal, 2-slider, 2-carousel

#50 [자유전공학부_곽승연] 3주차 넷플릭스
  README.md
  claude.txt
  css/category.css
  css/modal.css
  css/slider.css
  css/style.css
  index.html
  js/app.js
  js/modal.js
  js/slider.js
Labels: 2-modal, 2-slider, 2-carousel

#52 [국어국문학과_김남희] 넷플릭스 클론코딩 동적 기능 추가
  src/assets/icons/close.svg
  src/assets/images/movieDetailIcon.webp
  src/assets/images/movieDetailImg.webp
  src/components/appButton/appButton.js
  src/components/appButton/style.css
  src/components/appButton/template.html
  src/components/arrowButton/arrowButton.js
  src/components/arrowButton/style.css
  src/components/arrowButton/template.html
  src/components/faqAccordion/faqAccordion.js
  src/components/faqAccordion/style.css
  src/components/faqAccordion/template.html
  src/components/featureCard/featureCard.js
  src/components/featureCard/style.css
  src/components/featureCard/template.html
  src/components/languageSelect/languageSelect.js
  src/components/languageSelect/style.css
  src/components/languageSelect/template.html
  src/components/movieCard/movieCard.js
  src/components/movieCard/style.css
  src/components/movieCard/template.html
  src/components/movieModal/movieModal.js
  src/components/movieModal/style.css
  src/components/movieModal/template.html
  src/components/utils.js
  src/index.html
  src/scripts/index.js
  src/styles/globals.css
  src/styles/style.css
Labels: 2-modal, 2-carousel

#62 [컴퓨터공학부_류명현] 4주차 체크리스트
  README.md
Labels: 나만의체크포인트

#67 [지구환경과학부_편채범] 4주차 체크리스트 작성
  NETFLIX-CLONE-MIGRATED/.gitignore
  NETFLIX-CLONE-MIGRATED/data/netflix-content.json
  NETFLIX-CLONE-MIGRATED/index.html
  NETFLIX-CLONE-MIGRATED/package-lock.json
  NETFLIX-CLONE-MIGRATED/package.json
  NETFLIX-CLONE-MIGRATED/public/img/240_F_554944812_zVVODG8Qgfzl08ScezL4H9D9gFrgPAnW.jpg
  NETFLIX-CLONE-MIGRATED/public/img/attack-on-titan.jpg
  NETFLIX-CLONE-MIGRATED/public/img/attack-on-titan.png
  NETFLIX-CLONE-MIGRATED/public/img/banner-attack-on-titan.webp
  NETFLIX-CLONE-MIGRATED/public/img/icon/Netflix-Logo.jpg
  NETFLIX-CLONE-MIGRATED/public/img/icon/Netflix-Logo.png
  NETFLIX-CLONE-MIGRATED/public/img/icon/facebook-black-.png
  NETFLIX-CLONE-MIGRATED/public/img/icon/facebook-black.jpg
  NETFLIX-CLONE-MIGRATED/public/img/icon/free-icon-notification-bell-12328821.png
  NETFLIX-CLONE-MIGRATED/public/img/icon/free-icon-search-149852.png
  NETFLIX-CLONE-MIGRATED/public/img/icon/instagram-black-.png
  NETFLIX-CLONE-MIGRATED/public/img/icon/instagram-black.jpg
  NETFLIX-CLONE-MIGRATED/public/img/icon/instagram-black.png
  NETFLIX-CLONE-MIGRATED/public/img/icon/twitter-black-.png
  NETFLIX-CLONE-MIGRATED/public/img/icon/twitter-black.jpg
  NETFLIX-CLONE-MIGRATED/public/img/icon/user-icon.png
  NETFLIX-CLONE-MIGRATED/public/img/icon/youtube-black-.png
  NETFLIX-CLONE-MIGRATED/public/img/icon/youtube-black.jpg
  NETFLIX-CLONE-MIGRATED/public/img/poster/adolescence.jpg
  NETFLIX-CLONE-MIGRATED/public/img/poster/aema.jpg
  NETFLIX-CLONE-MIGRATED/public/img/poster/better-call-saul.jpg
  NETFLIX-CLONE-MIGRATED/public/img/poster/bon-appétit--Your-majesty.webp
  NETFLIX-CLONE-MIGRATED/public/img/poster/breaking-bad.webp
  NETFLIX-CLONE-MIGRATED/public/img/poster/demon-slayer-vertical.webp
  NETFLIX-CLONE-MIGRATED/public/img/poster/demon-slayer.webp
  NETFLIX-CLONE-MIGRATED/public/img/poster/designated-survivor.jpg
  NETFLIX-CLONE-MIGRATED/public/img/poster/esquire.webp
  NETFLIX-CLONE-MIGRATED/public/img/poster/eunjung-and-sangyeon.jpg
  NETFLIX-CLONE-MIGRATED/public/img/poster/little-island-big-hero.webp
  NETFLIX-CLONE-MIGRATED/public/img/poster/my-turn.webp
  NETFLIX-CLONE-MIGRATED/public/img/poster/queen-mantis.webp
  NETFLIX-CLONE-MIGRATED/public/img/poster/signal.webp
  NETFLIX-CLONE-MIGRATED/public/img/poster/suriname.jpg
  NETFLIX-CLONE-MIGRATED/public/img/poster/the-glory.jpg
  NETFLIX-CLONE-MIGRATED/public/img/poster/the-secrete-forest.webp
  NETFLIX-CLONE-MIGRATED/public/img/poster/trigger.jpg
  NETFLIX-CLONE-MIGRATED/public/img/poster/wednesday-vertical.jpg
  NETFLIX-CLONE-MIGRATED/public/img/poster/wednesday.jpg
  NETFLIX-CLONE-MIGRATED/public/vite.svg
  NETFLIX-CLONE-MIGRATED/src/index.html
  NETFLIX-CLONE-MIGRATED/src/script/content-loader.js
  NETFLIX-CLONE-MIGRATED/src/script/modal.js
  NETFLIX-CLONE-MIGRATED/src/script/slider_carousel.js
  NETFLIX-CLONE-MIGRATED/src/style/global.css
  NETFLIX-CLONE-MIGRATED/src/style/header-footer.css
  NETFLIX-CLONE-MIGRATED/src/style/slider.css
  NETFLIX-CLONE-MIGRATED/src/style/style.css
  NETFLIX-CLONE-MIGRATED/src/typescript.svg
  README.md
  img/icon/facebook-black.png
  src/script/slider_carousel.js
  src/style/style.css
Labels: 나만의체크포인트, 2-slider, 2-carousel, 3-fetch기반렌더링(Card-UI), 3-vite기반개발환경

#82 [자유전공학부_강수민] week4과제_빌드와 데이터통신
  .gitignore
  README.md
  app.js
  index.html
  modules/bookmark.js
  modules/carousel.js
  modules/like.js
  modules/movieLoader.js
  package-lock.json
  package.json
  public/mocks/movies.json
  style.css
Labels: 나만의체크포인트, 3-fetch기반렌더링(Card-UI), 3-vite기반개발환경
